using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LeetCode
{
//    You are given two strings s and t.

//String t is generated by random shuffling string s and then add one more letter at a random position.

//Return the letter that was added to t.


//Example 1:

//Input: s = "abcd", t = "abcde"
//Output: "e"
//Explanation: 'e' is the letter that was added.
//Example 2:

//Input: s = "", t = "y"
//Output: "y"



//Constraints:

//0 <= s.length <= 1000
//t.length == s.length + 1
//s and t consist of lowercase English letters.


    static class FindTheDifference
    {
       public static char FindTheDifferenceOwnSolution(string s, string t)
            {

            char[] string1 = s.ToCharArray();
            char[] string2 = t.ToCharArray();
            char difference = '0';
            Array.Sort(string1);
            Array.Sort(string2);

            for (int i = 0; i < string1.Length; i++)
            {
                if(string2[i] != string1[i])
                {
                    difference = string2[i];
                    break;
                }
            }
            if(difference == '0')
            {
                difference = string2.LastOrDefault();
            }

            return difference;
            }


        public static char FindTheDifferenceOneLiner(string s, string t)
        {
            return (char)(t.Sum(c => c) - s.Sum(c => c));
        }



    }

   

}
